### PR TITLE
Fix database hosts

### LINKED ISSUE #267: Creating a Database Host Function
# [ Explanation ]
I would like to suggest an edit to the wings installation script.

Recently it was implemented the option for you to create the user for the database host creation automatically.

### [ How it currently works ]
An option appears to choose whether or not you want a database host user.
If they choose "Yes", they will be prompted for a user and password, and that is it.

### [ How it could work ]
Before the "User" and "Password" questions appear, ask the user whether the host will be functional only locally, or externally.

### [ Examples: ]

Would you like to create your database host automatically? "Yes"
Will your host be accessible Locally, or externally? ( Local/External )

If the answer is "Local", do it the original way.
If "External", ask for the host IP.

### [ Why this change? ]

Well, the script will not be limited to always creating hosts locally, and it will have an option for this to work in both cases.

### PR DESCRIPTION
**Pull request by Linux123123**
Fixes #267 

Also adds restarting of `mysqld` to apply config changes.

### CODE REVIEW

**Comment by Linux123123** [comment]
We may as well open the port if user selected to configure firewall and mysql to be external.

File: install-wings.sh [hunk 1]
```diff
@@ -461,31 +463,59 @@ ask_database_user() {
...
-    ;;
-  centos)
-    sed -ne 's/^#bind-address=0.0.0.0$/bind-address=0.0.0.0/' /etc/my.cnf.d/mariadb-server.cnf
-    ;;
-  esac
+
+  if [ "$CONFIGURE_DBEXTERNAL" == true ]; then
+    case "$OS" in
+    debian | ubuntu)
+      sed -ne 's/^bind-address            = 127.0.0.1$/bind-address=0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf
```
Comment (vilhelmprytz) [inline install-wings.sh:510]: I just tried this locally, and this doesn't actually change anything. Perhaps this would work as well (I have tried it locally on Debian 11)?
```suggestion
      sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
```

**Review by vilhelmprytz — CHANGES_REQUESTED** [review]

File: install-wings.sh (hunk 1 above)
Comment (Linux123123) [reply install-wings.sh:510]: Yes, this is a problem. It was added in #220 and I have also encountered it not working. Your solutions works a lot better.

Comment (Linux123123) [reply install-wings.sh:510]: Is this also a problem for CentOS?

**Review by vilhelmprytz — APPROVED** [review]
LGTM 👍. Would you like to add so that the script opens 3306 if the user opts in?

**Comment by Linux123123** [comment]
> LGTM +1. Would you like to add so that the script opens 3306 if the user opts in?

Yes just added.

File: install-wings.sh [hunk 2]
```diff
@@ -461,31 +464,68 @@ ask_database_user() {
...
+    if [ "$CONFIRM_DBEXTERNAL_HOST" != "" ]; then
+      CONFIGURE_DBEXTERNAL_HOST="$CONFIRM_DBEXTERNAL_HOST"
+    fi
+    [ "$CONFIGURE_FIREWALL" == true ] && ask_database_firewall
+    CONFIGURE_DBEXTERNAL=true
+  fi
+}
+
+ask_database_firewall() {
+  echo -n "* Do you want to allow port 3306 threw the firewall? (y/N): "
```
Comment (vilhelmprytz) [inline install-wings.sh:488]:
```suggestion
  print_warning "Allow incoming traffic to port 3306 (MySQL) can potentially be a security risk, unless you know what you are doing!"
  echo -n "* Would you like to allow incoming traffic to port 3306? (y/N): "
```

**Review by vilhelmprytz — APPROVED** [review]

**Comment by vilhelmprytz** [comment]
Is it possible this PR solved #292 as well?

**Comment by vilhelmprytz** [comment]
Nevermind my previous message, the issue I mentioned should not be related 🙂
